[tool.poetry]
name = "dotfiles"
version = "0.3.3"
description = "My macOS configuration"
authors = ["zyz <zyzkyrie@outlook.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
