#!/usr/bin/env sh

/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
sudo /opt/homebrew/bin/yabai --load-sa

# bsp, stack or float
/opt/homebrew/bin/yabai -m config layout bsp
/opt/homebrew/bin/yabai -m config window_placement second_child

# general space settings
/opt/homebrew/bin/yabai -m config top_padding 00
/opt/homebrew/bin/yabai -m config bottom_padding 00
/opt/homebrew/bin/yabai -m config left_padding 00
/opt/homebrew/bin/yabai -m config right_padding 00
/opt/homebrew/bin/yabai -m config window_gap 10
# yabai -m config window_animation_duration    0.00

# global settings
/opt/homebrew/bin/yabai -m config focus_follows_mouse off
/opt/homebrew/bin/yabai -m config window_origin_display default
/opt/homebrew/bin/yabai -m config window_topmost off
/opt/homebrew/bin/yabai -m config window_shadow on
/opt/homebrew/bin/yabai -m config window_opacity on
/opt/homebrew/bin/yabai -m config window_opacity_duration 2000.0
/opt/homebrew/bin/yabai -m config active_window_opacity 1.0
/opt/homebrew/bin/yabai -m config normal_window_opacity 0.85
/opt/homebrew/bin/yabai -m config window_border off
/opt/homebrew/bin/yabai -m config window_border_width 6
/opt/homebrew/bin/yabai -m config active_window_border_color 0xff775759
/opt/homebrew/bin/yabai -m config normal_window_border_color 0xff555555
/opt/homebrew/bin/yabai -m config insert_feedback_color 0xffd75f5f
/opt/homebrew/bin/yabai -m config split_ratio 0.50
/opt/homebrew/bin/yabai -m config auto_balance off

# mouse settings
/opt/homebrew/bin/yabai -m config mouse_follows_focus on
/opt/homebrew/bin/yabai -m config mouse_modifier alt
# left click + drag
/opt/homebrew/bin/yabai -m config mouse_action1 move
# right click + drag
/opt/homebrew/bin/yabai -m config mouse_action2 resize

/opt/homebrew/bin/yabai -m config mouse_drop_action swap

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Disable specific apps
/opt/homebrew/bin/yabai -m rule --add app="^iStat*" sticky=on layer=above manage=off border=off
/opt/homebrew/bin/yabai -m rule --add app="^System Preferences*" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^System settings*" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^WeChat*" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^QQ*" manage=off

echo "yabai configuration loaded.."
